### ISSUE TITLE
.45 LC extends HDPistolAmmo unnecessarily 

### ISSUE THREAD

**Issue by UndeadZeratul** [HDest-Community/HDBulletLib-Recasted#17]
Prettyfist reported that because it extends off the 9mm ammo but doesn't use anything the class provides and doesn't override the `itemsThatUseThis` list, it's considered usable for 9mm weaponry.

Since it doesn't need anything from the current parent class, it can simply extend off of HDRoundAmmo instead.

**Comment by a1337spy** [comment]
done lol
